language: python
python:
  - 2.7
sudo: false
branches:
  only:
    - master
notifications:
  email:
    - pohl@physik.uni-bonn.de
 
# Setup miniconda with needed packages in a new virtual test-environment
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda info -a
  - conda create --yes -n test-environment numpy cython pytables scipy matplotlib pandas pyserial bitarray nose pyzmq pyyaml
  - source activate test-environment
  - pip install progressbar-latest pyvisa pyvisa-py

# Install pybar with needed packages
install:
  # Install prequisits (for FE-I4 analyis: pyBAR (needs basil and pySiLibUSB (needs pyusb)))
  # - pip install https://github.com/walac/pyusb/archive/master.zip
  # - pip install https://silab-redmine.physik.uni-bonn.de/attachments/download/735/pySiLibUSB-2.0.3.tar.gz
  # - pip install -e "git+https://github.com/SiLab-Bonn/basil.git@master#egg=basil&subdirectory=host"
  # - pip install -e "git+https://github.com/SiLab-Bonn/pyBAR.git@development"

  # Install pyTestbeamAnalysis
  - python setup.py develop

# Run test
script:
- nosetests tests/test_analysis.py tests/test_alignment_fixing
