name: test
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'cairo=1.14.6=0'
- !!python/unicode
  'cycler=0.10.0=py27_0'
- !!python/unicode
  'cython=0.25.2=py27_0'
- !!python/unicode
  'dbus=1.10.10=0'
- !!python/unicode
  'enum34=1.1.6=py27_0'
- !!python/unicode
  'expat=2.1.0=0'
- !!python/unicode
  'fontconfig=2.12.1=0'
- !!python/unicode
  'freetype=2.5.5=1'
- !!python/unicode
  'funcsigs=1.0.2=py27_0'
- !!python/unicode
  'glib=2.50.2=0'
- !!python/unicode
  'gst-plugins-base=1.8.0=0'
- !!python/unicode
  'gstreamer=1.8.0=0'
- !!python/unicode
  'hdf5=1.8.17=1'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'jpeg=8d=2'
- !!python/unicode
  'libffi=3.2.1=1'
- !!python/unicode
  'libgcc=5.2.0=0'
- !!python/unicode
  'libgfortran=3.0.0=1'
- !!python/unicode
  'libiconv=1.14=0'
- !!python/unicode
  'libpng=1.6.27=0'
- !!python/unicode
  'libxcb=1.12=1'
- !!python/unicode
  'libxml2=2.9.4=0'
- !!python/unicode
  'llvmlite=0.15.0=py27_0'
- !!python/unicode
  'matplotlib=1.5.3=np111py27_1'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'mock=2.0.0=py27_0'
- !!python/unicode
  'nose=1.3.7=py27_1'
- !!python/unicode
  'numba=0.30.1=np111py27_0'
- !!python/unicode
  'numexpr=2.6.1=np111py27_2'
- !!python/unicode
  'numpy=1.11.3=py27_0'
- !!python/unicode
  'openssl=1.0.2j=0'
- !!python/unicode
  'pbr=1.10.0=py27_0'
- !!python/unicode
  'pcre=8.39=1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'pixman=0.34.0=0'
- !!python/unicode
  'pycairo=1.10.0=py27_0'
- !!python/unicode
  'pyparsing=2.1.4=py27_0'
- !!python/unicode
  'pyqt=5.6.0=py27_1'
- !!python/unicode
  'pytables=3.3.0=np111py27_0'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'python-dateutil=2.6.0=py27_0'
- !!python/unicode
  'pytz=2016.10=py27_0'
- !!python/unicode
  'qt=5.6.2=2'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'scipy=0.18.1=np111py27_1'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'singledispatch=3.4.0.3=py27_0'
- !!python/unicode
  'sip=4.18=py27_0'
- !!python/unicode
  'six=1.10.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - alabaster==0.7.9
  - babel==2.3.4
  - docutils==0.12
  - imagesize==0.7.1
  - jinja2==2.8
  - markupsafe==0.23
  - pygments==2.1.3
  - snowballstemmer==1.2.1
  - sphinx==1.4.8
  - tables==3.3.0
  - travis-sphinx==1.4.2
